name: CI

on: [ pull_request ]

jobs:
  all:
    name: CI

    strategy:
      fail-fast: false # saves ci time, won't be worth it if it even runs other platform
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
        go-version: [ 1.16.0 ]
        target: [ 'all' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Setup Go binary path
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Setup Flutter Beta
        uses: subosito/flutter-action@v1
        with:
          channel: beta

      - name: Git line endings
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out THIS code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

      - name: make ${{ matrix.target }}
        run: |
          make $target
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
        env:
          target: ${{ matrix.target }}
        timeout-minutes: 20
